export const products = {
  starter: {
    id: 'starter',
    name: 'MB Starter',
    price: 2900,
    currency: 'eur',
    displayPrice: '29 €',
    description: 'Commence à structurer ton potentiel.',
    successPath: '/access?product=starter',
    contents: [
      'MB Score — Diagnostic stratégique',
      'Mini-manuel MB Starter',
      '30 règles Millionaire Behavior',
      'Checklist Potentiel Monétisable',
      'Plan 7 jours',
      'Guide d\'interprétation MB Score',
      '20 Money Moves simples',
    ],
  },
  core: {
    id: 'core',
    name: 'MB Core',
    price: 9700,
    currency: 'eur',
    displayPrice: '97 €',
    description: 'Le système complet MB.',
    successPath: '/access?product=core',
    contents: [
      'Tout dans Starter',
      'Manuel complet MB SYSTÈME',
      'MB Workbook complet',
      '100 Money Moves',
      'Scripts de vente',
      'Scripts de positionnement',
      'Plan 30 jours',
      'Templates d\'offre',
      'Checklist page de vente',
      'Checklist Stripe',
      '30 cartes Millionaire Behavior',
      'Guide image premium',
      'Guide offre sans audience',
    ],
  },
  pro: {
    id: 'pro',
    name: 'MB Pro',
    price: 19700,
    currency: 'eur',
    displayPrice: '197 €',
    description: 'Templates, scripts et outils avancés.',
    successPath: '/access?product=pro',
    contents: [
      'Tout dans Core',
      'Générateur d\'offre',
      'Générateur de bio premium',
      'Générateur de posts',
      'Scripts DM avancés',
      'Calendrier contenu 30 jours',
      'Prompts IA MB',
      'Modèles landing page',
      'Modèle page Stripe',
      'Système de lancement 7 jours',
      'Système de lancement 30 jours',
      'Kit internationalisation FR/EN',
      'Swipe file hooks FR/EN',
      'Dashboard structure',
    ],
  },
} as const;

export type ProductKey = keyof typeof products;
